PidFile=/tmp/zabbix_agent2.pid
LogType=console
Server=zabbix-server
ServerActive=zabbix-server
Hostname=linux-monitorado
ListenPort=10050

AllowKey=system.run[/usr/local/bin/start-squid.sh,*]
Plugins.SystemRun.LogRemoteCommands=1
